[project]
name = "vigilancia-dengue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Renan Croffi", email = "renancroffi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "requests>=2.34.2",
    "seaborn>=0.13.2",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
[tool.pytest.ini_options]
pythonpath = ["src"]